name: Cypress Tests

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '05 19 * * FRI'

jobs:
  # install:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Cypress install
  #       uses: cypress-io/github-action@v6
  #       with:
  #         # Disable running of tests within install job
  #         runTests: false
  #         build: npm run build

  #     - name: Save build folder
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: build
  #         if-no-files-found: error
  #         path: dist

  cypress-run:
    runs-on: ubuntu-latest
    # needs: install
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2, 3] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Download the build folder
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: build

      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # Records to Cypress Cloud 
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
          parallel: true # Runs test in parallel using settings above
          group: "Tee Times"
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}